FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_DB=mysql
ENV KC_DB_URL_HOST=64.227.128.119
ENV KC_DB_URL_PORT=3306
ENV KC_DB_URL_DATABASE=keycloak
ENV KC_DB_USERNAME=hrms_test
ENV KC_DB_PASSWORD=rooT@3225
ENV KC_HOSTNAME_STRICT=false
ENV KC_PROXY=edge

EXPOSE 8080

# SIMPLE - just the command
CMD start-dev
