FROM quay.io/keycloak/keycloak:latest

# Environment variables
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_DB=mysql
ENV KC_DB_URL=jdbc:mysql://64.227.128.119:3306/keycloak?useSSL=true&allowPublicKeyRetrieval=true
ENV KC_DB_USERNAME=hrms_test
ENV KC_DB_PASSWORD=rooT@3225

# Expose port
EXPOSE 8080

# Start command (use full path to be safe)
CMD ["/opt/keycloak/bin/kc.sh", "start-dev"]