FROM bitnami/keycloak:latest

ENV KEYCLOAK_ADMIN_USER=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KEYCLOAK_DATABASE_HOST=64.227.128.119
ENV KEYCLOAK_DATABASE_PORT=3306
ENV KEYCLOAK_DATABASE_NAME=keycloak
ENV KEYCLOAK_DATABASE_USER=hrms_test
ENV KEYCLOAK_DATABASE_PASSWORD=rooT@3225

EXPOSE 8080
